{% set name = "xarray-ceos-alos2" %}
{% set version = "2023.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xarray-ceos-alos2-{{ version }}.tar.gz
  sha256: db3e95bc4f7cbfc631bc720d97b0c18bf0ad794fc4c9d648133567347e6e8420

build:
  noarch: python
  entry_points:
    - ceos-alos2-create-cache = ceos_alos2.sar_image.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=64.0
    - setuptools-scm
    - pip
  run:
    - python >=3.10
    - cytoolz
    - python-dateutil
    - xarray
    - xarray-datatree
    - numpy
    - construct >=2.10
    - fsspec
    - platformdirs
    - exceptiongroup

test:
  imports:
    - ceos_alos2
  commands:
    - pip check
    - ceos-alos2-create-cache --help
  requires:
    - pip

about:
  home: https://github.com/umr-lops/xarray-ceos-alos2
  summary: xarray reader for advanced land observing satellite 2 (ALOS2) CEOS files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - keewis
    - agrouaze
